### ISSUE TITLE
GetUpcoming_ShouldReturnAllUpcomingAppointments Test in AppointmentsRepositoryTests.cs doesn't use method that is to be implemented

### ISSUE THREAD

**Issue by AndreasStgm** [pxlit-projects/Guts-DotNetAdvanced-23-24#2]
`GetUpcoming_ShouldReturnAllUpcomingAppointments` test does not use the `GetUpcomingAppointments` method. Instead it uses the `GetAppointmentsForPatient` method, this makes it that if this method is implemented the `GetUpcoming_ShouldReturnAllUpcomingAppointments` test is always successful even when not implemented.

![image](https://github.com/pxlit-projects/Guts-DotNetAdvanced-23-24/assets/80055332/4e8f6412-937b-4c95-8e35-947825cf3f12)

![image](https://github.com/pxlit-projects/Guts-DotNetAdvanced-23-24/assets/80055332/dac1786a-8e3d-4129-9319-da9d52e75e90)

**Comment by Adrigorithm** [comment]
same here. (ps. update to .net8 🙃)

**Comment by marijkewillems** [comment]
Test is aangepast, zie announcement op Blackboard.
